// Bundles the AppStorageFacet (src/agent/facet/entry.ts) — including the
// tree-shaken @cloudflare/dofs filesystem layer — into a single ESM string and
// writes it to src/agent/facet/bundle.generated.ts.
//
// WHY: the facet runs as a separately-loaded Durable Object (via the Worker
// Loader / `getDurableObjectClass`), so its code must be delivered as source,
// not imported into the host worker. Bundling it here at build time keeps dofs
// OUT of the host worker's bundle (a real trim) and tree-shakes dofs down to
// only what the filesystem layer needs.
//
// Run automatically before dev/deploy/typecheck (see package.json pre-scripts),
// or manually with `npm run build:facet`.

import { build } from "esbuild";
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const entry = resolve(root, "src/agent/facet/entry.ts");
const outFile = resolve(root, "src/agent/facet/bundle.generated.ts");

const result = await build({
  entryPoints: [entry],
  bundle: true,
  format: "esm",
  target: "es2022",
  platform: "neutral",
  // Runtime builtins resolved by workerd (facet loads with nodejs_compat).
  external: ["cloudflare:workers", "node:crypto", "node:events"],
  minify: true,
  legalComments: "none",
  write: false
});

const code = result.outputFiles[0].text;

const header =
  "// AUTO-GENERATED by scripts/build-facet.mjs — do not edit by hand.\n" +
  "// Bundled source of AppStorageFacet, including the tree-shaken\n" +
  "// @cloudflare/dofs filesystem layer. Delivered to the Worker Loader so the\n" +
  "// facet runs with its own isolated SQLite. Regenerate with `npm run build:facet`.\n";

writeFileSync(
  outFile,
  `${header}export const APP_STORAGE_FACET_SOURCE = ${JSON.stringify(code)};\n`
);

console.log(
  `build-facet: wrote ${outFile} (${(code.length / 1024).toFixed(1)} KiB of facet source)`
);
